### ISSUE TITLE
Why use "People's Republic of China" for simplified Chinese characters and "Taiwan" for traditional Chinese characters?

### ISSUE THREAD

**Issue by abcdefg233** [LuaLS/LuaLS.github.io#11]
[translations.mdx](https://github.com/LuaLS/LuaLS.github.io/blob/main/src/content/wiki/translations.mdx)
```mdx
| [zh-cn] | Chinese - People's Republic of China |
| [zh-tw] |           Chinese - Taiwan           |
```

为什么要用”People's Republic of China“代表简化汉字，而”Taiwan“代表台湾传统汉字？我们明明有更加准确和政治中立的名词区分这两个概念：Chinese Simplified，Chinese Traditional。

Why use "People's Republic of China" for simplified Chinese characters and "Taiwan" for traditional Chinese characters?
We clearly have more accurate and politically neutral terms to distinguish between these two concepts: Chinese Simplified, Chinese Traditional.

**Comment by abcdefg233** [comment]
想体现传统汉字在香港和台湾的区别，可以在 Chinese Traditional 后加上 “(香港)”“(台湾)”的后缀

To reflect the difference between traditional Chinese characters in Hong Kong and Taiwan, you can add the suffixes "(Hong Kong)" and "(Taiwan)" after Chinese Traditional

**Comment by abcdefg233** [comment]
[language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)
![image](https://github.com/LuaLS/LuaLS.github.io/assets/32760059/f006edb5-221a-4f64-84dc-cf9e5d793fa2)
![image](https://github.com/LuaLS/LuaLS.github.io/assets/32760059/0c2524bc-76f0-4e4a-b9b7-2d94b458db75)

**Comment by carsakiller** [comment]
These are the names given by Microsoft for the [BCP 47 language code](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a).

**Comment by abcdefg233** [comment]
Okey.
