### ISSUE TITLE
Annotation outline behavior is broken

### ISSUE THREAD

**Issue by Fireboyd78** [LuaLS/LuaLS.github.io#26]
Below should be self-explanatory what's happening. You try to click on something and it doesn't scroll correctly.

![chrome_G2a7Mx0zT6](https://github.com/LuaLS/LuaLS.github.io/assets/2906983/8905a68f-b050-4690-b1ef-b643eab2f7d1)

This is rather quite frustrating, because trying to refer to the documentation is basically made impossible with this unfriendly behavior.

**Browser:** Chrome Version 122.0.6261.70 (Official Build) (64-bit)

**Comment by Fireboyd78** [comment]
This issue was caused by commit 3bd0c0d, you can see [here](https://github.com/LuaLS/LuaLS.github.io/commit/3bd0c0d558909a747fa5d4635dc45c5caecaa9e7#r139019111) the block of code that is responsible for this.

**Comment by carsakiller** [comment]
Interesting… I knew chrome by default has smooth scrolling disabled, and it must be manually enabled using an [experimental flag](https://www.geeksforgeeks.org/how-to-enable-or-disable-smooth-scrolling-in-google-chrome/), but it looks like with smooth scrolling disabled, this problem does not occur. It is only if I enable experimental smooth scrolling that I experience this issue.

We may have to find a way to disable smooth scrolling in chrome, or just disable it all together. Both are not ideal.

**Comment by carsakiller** [comment]
I am running chrome in Windows Sandbox and when the sandbox is in windowed mode, I experience this issue, but when I fullscreen it, it works as expected. Very weird...

**Comment by carsakiller** [comment]
Now I have installed Chrome locally and cannot reproduce at all.

**Comment by Fireboyd78** [comment]
@carsakiller Can you verify that removing the code I linked to still results in the expected behavior?

**Comment by carsakiller** [comment]
Chrome seems to be unable to scroll in two containers at once. When the article is scrolled down, the sidebar scrolls to match, which Chrome seems to take issue with.

I wanted to listen to the [`scrollend` event](https://caniuse.com/mdn-api_element_scrollend_event) and just scroll the sidebar when the main content scrolling is finished, but unfortunately, Safari/WebKit does not support it. I have instead opted to just listen for debounced scroll events and scroll the sidebar when that is finished. Let me know if this works for you 🙂

**Comment by carsakiller** [comment]
@Fireboyd78 no problem!

I didn't know the scrolling to IDs was also broken in chrome 😟. Turns out that the basic lazy-loading of images I had in articles caused the scrolling to break. I know the long-term solution, but for now I have just removed lazy loading and forced browsers to scroll to the targeted ID on page load.

Let me know if there are any other issues, you've been very helpful!
